### ISSUE TITLE
Painting, color fill, VIPS library error, (WinXP).

### ISSUE THREAD

**Issue by MvGulik** [jcupitt/nip2#47]
Checked against: Nip2 7.42.1 (but its not limited to this version)
OS: Win.XP
MEM: 3GB (max for this XP)

When color filling relative large images, at some point a general "VIPS library error." (no other info shown in error message) is triggered when doing a fill. When this happens (at X number of color fills) depends on the size of the image.

When the undo buffer is cleared, a other set of fill actions can be done again. (unless the size of the image is triggering the error on the first fill action)

(Making use of undo after this error might trigger a additional terminal nip2 error on closing nip2.)

Just in case. I have set the nip2 temp folder to a drive with plenty of free space. But the drive where nip2 is installed has less than 10GB of free space. (Main Windows drive)

**Comment by jcupitt** [comment]
Hi, yes, it'll run out of memory at some point. It needs to keep a copy of the whole of the image during a flood fill.

You can limit the number of undo buffers. Set it to a smallish number (five perhaps?) and the error should stop. You can set this limit in the Preferences dialog, under "paintbox".

**Comment by MvGulik** [comment]
Aha, Clear. Will do.
Thanks. :)
