### ISSUE TITLE
Install with Homebrew in Mac OS

### ISSUE THREAD

**Issue by paazmaya** [jcupitt/nip2#48]
Is there any reason why `nip2` is not available via `brew` since it seems to be available [1] via `fink` and `port`?

[1] http://www.vips.ecs.soton.ac.uk/index.php?title=Build_on_OS_X

**Comment by jcupitt** [comment]
Hi, last time I checked some of the packages nip2 needs were not available as formula. That was a while ago, perhaps they are there now.

I agree, a nip2 formula would be handy.

**Comment by paazmaya** [comment]
@jcupitt thank you for the info. Please let me know if there is anything I could to do help, without having the understanding of the Homebrew internals...

**Comment by jcupitt** [comment]
I'll try a nip2 homebrew again tonight, perhaps it's possible now.

**Comment by paazmaya** [comment]
Thank you!

**Comment by jcupitt** [comment]
I've made a nip2 formula and put in a pull request. It may get added in a couple of days.

**Comment by paazmaya** [comment]
Great to hear! Looking forward to it with Yosemite and [whatever the earlier versions was called] ready

**Comment by jcupitt** [comment]
This is in homebrew now, I'll close.
