### ISSUE TITLE
How to convert a number to a string?

### ISSUE THREAD

**Issue by denilsonsa** [jcupitt/nip2#52]
I'm trying to generate a list of filenames from numbers, but I'm failing to convert a number to a string.

This is obviously wrong: `[ "foo" ++ [row] ++ ".png"  :: row <- [0..2] ]`

    $ nip2 --version
    nip2-7.40.4
    linked to vips-7.40.6-Thu Dec  4 13:43:24 UTC 2014

Installed on Ubuntu 15.04 using `apt-get`. I see a new `libvips` and `nip2` version is available, it would be great to have them on Debian/Ubuntu.

**Comment by jcupitt** [comment]
Hi, `print` is a built-in which converts anything to a string. For example:

```
["hello " ++ print x :: x <- [1..]]
```
