### ISSUE TITLE
8.3.0 builds with debugging by default

### ISSUE THREAD

**Issue by bgilbert** [jcupitt/nip2#58]
`configure.ac` still contains [logic](https://github.com/jcupitt/nip2/blob/fcc05e73c509236444de9362703658758719410a/configure.ac#L69-L71) to enable debugging when the minor version is odd.  I assume this rule is defunct in 8.x?

**Comment by jcupitt** [comment]
Oops, thanks Benjamin. Fix will land in 8.3.1 I guess. I'm making a win binary at the moment, and homebrew I guess, so there will probably be some more tweaks to come.
