### ISSUE TITLE
Slight tendency to crash on opening multiple images (Win, drag&drop)

### ISSUE THREAD

**Issue by MvGulik** [jcupitt/nip2#62]
As the title say, nip2 - 8.4.0 seems to have a slight habit of crashing after adding multiple images (lets say number of images >10) with a drag and drop action (windows).
- *note: current only using nip2-v8.4.0 (*first v8.n I used*) and nip2-v7.42.1 (*fallback*), so don't know to which nip2 version it might be related.*

So far I have not found any possible potential related reasons, as its seems devoid of any stable reproducibility (so far).

The first encountered case, that did seem to happen regularly, was in a particular work-space-file. But while trying to hunt down the potential crash-trigger. It disappeared again (also while using the source work-space where is happened in the first place). 
- The only thing that seems to stands out here was that I did a nip2/VIPS temporary cache clearing (*on nip2 startup prompt*)

The second case was in a newly+empty opened work-space (*I did clear the cache, just not sure if I did it on the first case (probably), or the second case.*). At the second try, dropping in the same set of file, in a newly+empty opened work-space there was no crash.

If the cache content 'is' somehow involved, ... I'm not sure if I can track it down successfully. (*presuming its a Windows specific hiccup.*)

Last version encountered: Nip2 - v8.4.0
OS: Windows XP
######  (*I know, I should switch to something ... else. At least that's what the democratic majority seems to suggest/demand.*)

**Comment by MvGulik** [comment]
Closing until re-detected in version 8.5.0

###### (Trying first steps towards Linux ...)

**Comment by jcupitt** [comment]
I did find a bug related to operator caching yesterday which could trigger crashes under some circumstances. Try with 8.5.1, it might be fixed.

**Comment by MvGulik** [comment]
Roger.

Might be a bit of a problem, as I have not found a good way to consistently reproduce this behavior in the older versions. (*will see about giving that part a other go.*)
