### ISSUE TITLE
16-bit sRGB png image from ImageMagick: merely "RGB16" but neither linear nor nonlinear?

### ISSUE THREAD

**Issue by DavidRosen** [jcupitt/nip2#64]
I have an image that was in "sRGB" colorspace in ImageMagick, which wrote it to a 16-bit PNG file.  When I read it into nip2, it is labeled as merely "RGB16" -- how can I specify, or how can nip2 know, what the image data represents?  It appears to display it correctly, so is it assuming that RGB16 always has an sRGB nonlinearity?

**Comment by jcupitt** [comment]
Hello, yes, libvips assumes every image without an ICC profile is sRGB, so RGB16 is 16-bit sRGB. It's called RGB16 for historical reasons.

**Comment by DavidRosen** [comment]
Thank you.
