### ISSUE TITLE
Workspace File, Relative Image path, ? (linux)

### ISSUE THREAD

**Issue by MvGulik** [jcupitt/nip2#66]
I'm trying to adjust the 'image_file' path inside the nip2 workspace file.
(*so I can use the same WS file on same named, but in separate folders, image sets.*)

I tried a number of variations, like:
\- `<iText formula="Image_file &quot;0_0.jpeg&quot;"/>`
\- `<iText formula="Image_file &quot;./0_0.jpeg&quot;"/>`
\- `<iText formula="Image_file &quot;$/0_0.jpeg&quot;"/>`
But either (*after loaded the workspace file into nip2*) a leading "$HOME/" is added to the image-path, or "/home/" in some cases, or it just is (*or turns into*) the other absolute path variation. (*ie: "/<path and/or filespec>"*)

Is what I try to do here actually possible or supported ?
(*On Linux. Worked okay on Windows if I recall correctly, but that was probably still on nip2 version 7.x*)
(*Linux: Mint 18 Cinnamon*)
(*Nip2 version: 8.2*)...(*not yet comfortable with trying to manual upgrading nip2*)

**Comment by jcupitt** [comment]
Hello, this should be automatic, if you move the ws file and the images. 

ws files have their path recorded inside when you save them, say `/a/b/something.ws`. When you load a ws from (for example) `/c/d/something.ws`, it notices that the location has changed. If that ws in turn loads a file from `/a/b/something.tif`, that path will be automatically changed to `/c/d/something.tif`.

The idea is that you can make a folder of images plus a ws file, and move that folder around without things breaking, even on Windows where there isn't really the idea of a current directory.

For you case, if you have two folders full of images, just copying the ws file across should be enough (I think).

**Comment by MvGulik** [comment]
Aha. Yea that's working.
Thanks.

*I think I dismissed/ignored some similar writing (*I read some time ago*) about nip2 path changes.*
*Sorry.*

(*Closing*)
