### ISSUE TITLE
CMYK tif image not display right

### ISSUE THREAD

**Issue by jindili** [jcupitt/nip2#71]
rgb & cmyk file in windows explorer thumbnail
same image in rgb & cmyk format
![image](https://user-images.githubusercontent.com/73845/38011771-4fda21ca-3291-11e8-879e-f55ef004debb.png)

in nip2 
![image](https://user-images.githubusercontent.com/73845/38011820-80c2b978-3291-11e8-9de7-a39708680f55.png)

zoom up
![image](https://user-images.githubusercontent.com/73845/38011831-8ca6c2a2-3291-11e8-89f8-b04d38b7d5c7.png)

My nip2 version:
$PACKAGE: nip2
$VERSION: 8.6.0
$VIPSHOME: D:\apps\VIPS\nip2-8.6.0

**Comment by jcupitt** [comment]
Hello, nip2 does not import device space images automatically -- it always just sends the first three channels to the display. 

Click Toolkits / Colour / ICC / Import to import to PCS.

**Comment by jindili** [comment]
Yes,  it is.
select image imported and Click Toolkits / Colour / ICC / Import to import to PCS.
Now display right.
