### ISSUE TITLE
make check-TESTS fails

### ISSUE THREAD

**Issue by ggardet** [jcupitt/nip2#72]
The tests fails on libpng errors due to broken PNG files. If I run, `optipng -quiet -force -fix` on each PNG files to fix the files, then I get the following errors on im_max function:

make  check-TESTS 
[  104s] make[2]: Entering directory '/home/abuild/rpmbuild/BUILD/nip2-8.6.0/test' 
[  104s] make[3]: Entering directory '/home/abuild/rpmbuild/BUILD/nip2-8.6.0/test' 
[  450s] FAIL: test_all.sh
[  450s] =====================================
[  450s]    nip2 8.6.0: test/test-suite.log
[  450s] =====================================
[  450s] 
[  450s] # TOTAL: 1
[  450s] # PASS:  0
[  450s] # SKIP:  0
[  450s] # XFAIL: 0
[  450s] # FAIL:  1
[  450s] # XPASS: 0
[  450s] # ERROR: 0
[  450s] 
[  450s] .. contents:: :depth: 2
[  450s] 
[  450s] FAIL: test_all.sh
[  450s] =================
[  450s] 
[  450s] testing big_and_small_disks.ws ... ok
[  450s] testing test_colour.ws ... ok
[  450s] testing test_conv.ws ... ok
[  450s] testing test_fail.ws ... --test: errors found
[  450s] error in "A3" (A3 - $VIPSHOME/test/workspaces/test_fail.ws): sane!
[  450s] fail expected
[  450s] testing test_filter.ws ... ok
[  450s] testing test_fourier.ws ... ok
[  450s] testing test_histogram.ws ... ok
[  450s] testing test_image.ws ... ok
[  450s] testing test_math.ws ... ok
[  450s] testing test_matrix.ws ... ok
[  450s] testing test_stats.ws ... ok
[  450s] testing test_tasks.ws ... --test: errors found
[  450s] error in "IB10" (IB10 - $VIPSHOME/test/workspaces/test_tasks.ws): Error calling library function "im_max" (maximum value of image).
[  450s] VIPS library: max: parameter out not set
[  450s] 
[  450s] You passed:
[  450s]    in - 500x500 32-bit float, 3 bands, histogram
[  450s] 
[  450s] Usage:
[  450s] CALL operator "im_max"
[  450s] maximum value of image, from package "arithmetic"
[  450s] "im_max" takes 1 argument:
[  450s]    in  - image
[  450s] And produces 1 result:
[  450s]    value  - double
[  450s] Flags:
[  450s]    (PIO function) (no coordinate transformation) (area operation) (operation can be cached)
[  450s] 
[  450s] failed
[  450s] testing test_widgets.ws ... ok
[  450s] testing test_snip.def ... ok
[  450s] testing 1pt_mosaic.ws ... ok
[  450s] testing 2pts_mosaic.ws ... ok
[  450s] testing businesscard.ws ... ok
[  450s] testing clone.ws ... ok
[  450s] testing logo2.ws ... ok
[  450s] testing manual_balance.ws ... --test: errors found
[  450s] error in "B2" (B2 - $VIPSHOME/share/nip2/data/examples/manual_balance/manual_balance.ws): Error calling library function "im_max" (maximum value of image).
[  450s] VIPS library: max: parameter out not set
[  450s] 
[  450s] You passed:
[  450s]    in - 500x500 32-bit float, 3 bands, histogram
[  450s] 
[  450s] Usage:
[  450s] CALL operator "im_max"
[  450s] maximum value of image, from package "arithmetic"
[  450s] "im_max" takes 1 argument:
[  450s]    in  - image
[  450s] And produces 1 result:
[  450s]    value  - double
[  450s] Flags:
[  450s]    (PIO function) (no coordinate transformation) (area operation) (operation can be cached)
[  450s] 
[  450s] failed
[  450s] testing overlay_blend.ws ... ok
[  450s] repeating tests with the vectorising system disabled
[  450s] testing big_and_small_disks.ws ... ok
[  450s] testing test_colour.ws ... ok
[  450s] testing test_conv.ws ... ok
[  450s] testing test_fail.ws ... --test: errors found
[  450s] error in "A3" (A3 - $VIPSHOME/test/workspaces/test_fail.ws): sane!
[  450s] fail expected
[  450s] testing test_filter.ws ... ok
[  450s] testing test_fourier.ws ... ok
[  450s] testing test_histogram.ws ... ok
[  450s] testing test_image.ws ... ok
[  450s] testing test_math.ws ... ok
[  450s] testing test_matrix.ws ... ok
[  450s] testing test_stats.ws ... ok
[  450s] testing test_tasks.ws ... --test: errors found
[  450s] error in "IB10" (IB10 - $VIPSHOME/test/workspaces/test_tasks.ws): Error calling library function "im_max" (maximum value of image).
[  450s] VIPS library: max: parameter out not set
[  450s] 
[  450s] You passed:
[  450s]    in - 500x500 32-bit float, 3 bands, histogram
[  450s] 
[  450s] Usage:
[  450s] CALL operator "im_max"
[  450s] maximum value of image, from package "arithmetic"
[  450s] "im_max" takes 1 argument:
[  450s]    in  - image
[  450s] And produces 1 result:
[  450s]    value  - double
[  450s] Flags:
[  450s]    (PIO function) (no coordinate transformation) (area operation) (operation can be cached)
[  450s] 
[  450s] failed
[  450s] testing test_widgets.ws ... ok
[  450s] testing test_snip.def ... ok
[  450s] testing 1pt_mosaic.ws ... ok
[  450s] testing 2pts_mosaic.ws ... ok
[  450s] testing businesscard.ws ... ok
[  450s] testing clone.ws ... ok
[  450s] testing logo2.ws ... ok
[  450s] testing manual_balance.ws ... --test: errors found
[  450s] error in "B2" (B2 - $VIPSHOME/share/nip2/data/examples/manual_balance/manual_balance.ws): Error calling library function "im_max" (maximum value of image).
[  450s] VIPS library: max: parameter out not set
[  450s] 
[  450s] You passed:
[  450s]    in - 500x500 32-bit float, 3 bands, histogram
[  450s] 
[  450s] Usage:
[  450s] CALL operator "im_max"
[  450s] maximum value of image, from package "arithmetic"
[  450s] "im_max" takes 1 argument:
[  450s]    in  - image
[  450s] And produces 1 result:
[  450s]    value  - double
[  450s] Flags:
[  450s]    (PIO function) (no coordinate transformation) (area operation) (operation can be cached)
[  450s] 
[  450s] failed
[  450s] testing overlay_blend.ws ... ok
[  450s] 
[  450s] ============================================================================
[  450s] Testsuite summary for nip2 8.6.0
[  450s] ============================================================================
[  450s] # TOTAL: 1
[  450s] # PASS:  0
[  450s] # SKIP:  0
[  450s] # XFAIL: 0
[  450s] # FAIL:  1
[  450s] # XPASS: 0
[  450s] # ERROR: 0
[  450s] ============================================================================
[  450s] See test/test-suite.log
[  450s] Please report to vipsip@jiscmail.ac.uk
[  450s] ============================================================================
[  450s] make[3]: *** [Makefile:565: test-suite.log] Error 1
[  450s] make[3]: Leaving directory '/home/abuild/rpmbuild/BUILD/nip2-8.6.0/test'
[  450s] make[2]: *** [Makefile:673: check-TESTS] Error 2
[  450s] make[2]: Leaving directory '/home/abuild/rpmbuild/BUILD/nip2-8.6.0/test'
[  450s] make[1]: *** [Makefile:743: check-am] Error 2
[  450s] make[1]: Leaving directory '/home/abuild/rpmbuild/BUILD/nip2-8.6.0/test'
[  450s] make: *** [Makefile:561: check-recursive] Error 1

Please note that I use libvips 8.5.9 and I tried nip2 in version 8.6.0, 8.5.2 and 8.4.0.

**Comment by jcupitt** [comment]
Huh curious, I wonder when libpng stopped reading that image. I'll see if I can fix it.

**Comment by jcupitt** [comment]
Their fix just truncated the PNG for me. I was able to load it on an old Ubuntu 16.04 machine, resave as TIFF, then resave as PNG on a current machine. Phew!

I'll see if that fixes make check.

**Comment by jcupitt** [comment]
`make check` now passes for me with this fixed file. 

Thank you for reporting this @ggardet !

**Comment by ggardet** [comment]
Fixed make check for me too.
Thanks a lot!
